GET http://localhost:3000/products

###

POST http://localhost:3000/products
Content-Type: application/json

{
    "image_url": "https://cdn.barbora.lt/products/6dc50b1e-4336-415c-9fce-f4d72a15bf86_m.png",
    "title": "Pienas, 2,5% rieb. DVARO, pak. 1L, 1 l",
    "description": "DVARO pienas yra šviežio skonio.",
    "price": 1.29
}

###
DELETE http://localhost:3000/products/57

###

GET http://localhost:3000/totalproducts

###